import MicroLEDModel from "./microled_model.jsx";
import React, { useState } from "react";
import '../styles/microled.css';
import '../styles/pagebg.css';
import '../styles/era.css';

const BASE_URL = import.meta.env.BASE_URL || "/";

{/*
    MicroLED Parts Information:
    label: Name of MicroLED Part
    description: MicroLED Part Description
    processMicroledTitle: Name of the Process Associated with the Part
    processMicroledDescription: Description of the Associated Process
*/}
const PARTS = [
    {
        id: "backplane",
        label: "TFT Backplane",
        description:
            "A thin-film transistor array that drives current to each micro-LED chip individually, controlling how bright every sub-pixel glows.",
        processMicroledTitle: "Driving the Chips",
        processMicroledDescription:
            "Each transistor in the backplane acts as a switch, delivering a precise amount of current to the chip sitting above it. Varying that current changes how much light the chip emits, which is how each sub-pixel's brightness is controlled independently.",
    },
    {
        id: "chips",
        label: "Micro-LED Chips",
        description:
            "Thousands of microscopic self-emitting diodes. Each pixel is built from a red, green, and blue chip that light up independently, without needing a backlight.",
        processMicroledTitle: "Light Emission",
        processMicroledDescription:
            "When current reaches a chip, electrons and holes recombine inside its semiconductor material and release energy as light. Because red, green, and blue chips can each be driven to a different brightness, combining their output produces every color the pixel displays.",
    },
    {
        id: "electrode",
        label: "Common Electrode",
        description:
            "A shared, transparent conductive layer above the chip array that completes the circuit, carrying current out of each chip's top contact.",
        processMicroledTitle: "Completing the Circuit",
        processMicroledDescription:
            "Current flows from the backplane up into the bottom of each chip, then out through its top contact into this shared electrode layer above it. This gives every chip a return path without needing a separate wire for each one.",
    },
    {
        id: "cover",
        label: "Cover Glass",
        description:
            "A protective transparent layer sealing the panel and letting the light emitted below pass through to the viewer.",
        processMicroledTitle: "Light Transmission",
        processMicroledDescription:
            "Light generated by the chips travels upward through the electrode and exits through the cover glass. This final layer protects the delicate chip array underneath while staying optically clear enough not to distort or dim the image.",
    },
];

export default function MicroLEDViewer() {
    const [selectedPart, setSelectedPart] = useState('backplane');
    const [animate, setAnimate] = useState(false);

    const activeBtn = (current, target) => `btn ${current === target ? 'active' : ''}`;
    const activeInfo = PARTS.find((p) => p.id === selectedPart) || PARTS[0];

    return (
        <div>
            <div className="bg"></div>
            <div className="back-button-container" style={{ padding: '0.5rem' }}>
                <a href={`${BASE_URL}/displays`} className="link-pill lower">
                    ← Go Back
                </a>
            </div>
            <div className="microled-split-layout">

                {/* LEFT SIDE: Information Display */}
                <div className="microled-info-side">
                    <h2 className="microled-info__title">{activeInfo.label}</h2>
                    <p className="microled-info__desc">{activeInfo.description}</p>

                    <div className="microled-dynamic-box" style={{ marginTop: '2rem' }}>
                        <h3 className="microled-info__title">{activeInfo.processMicroledTitle}</h3>
                        <p className="microled-info__desc">{activeInfo.processMicroledDescription}</p>
                    </div>
                </div>

                {/* RIGHT SIDE: Controls and 2D Model */}
                <div className="microled-model-side">
                    {/* 2D Model Parts */}
                    <div className="controls">
                        <span>Parts:</span>
                        <button className={activeBtn(selectedPart, 'backplane')} onClick={() => setSelectedPart('backplane')}>Backplane</button>
                        <button className={activeBtn(selectedPart, 'electrode')} onClick={() => setSelectedPart('electrode')}>Electrode</button>
                        <button className={activeBtn(selectedPart, 'chips')} onClick={() => setSelectedPart('chips')}>Chips</button>
                        <button className={activeBtn(selectedPart, 'cover')} onClick={() => setSelectedPart('cover')}>Cover</button>
                    </div>

                    {/* Light Control */}
                    <div className="controls">
                        <span>Action:</span>
                        <button className={activeBtn(animate, true)} onClick={() => setAnimate(!animate)}>
                            {animate ? 'Stop Light' : 'Animate Light'}
                        </button>
                    </div>

                    <MicroLEDModel selectedPart={selectedPart} setSelectedPart={setSelectedPart} animate={animate} />
                </div>

            </div>
        </div>
    );
}